export const SESSION_PROVIDER_IDS = [
  "codex",
  "claude",
  "gemini",
  "grokbuild",
  "opencode",
  "openclaw",
  "hermes",
  "pi",
  "dsh",
  "kimi",
  "zcode",
  "qoder",
  "qwen",
  "workbuddy",
  "antigravity",
  "cursor",
  "kilocode",
  "cline",
  "goose",
  "zed",
  "mimocode",
  "reasonix",
  "continue",
  "crush",
  "teleagent",
] as const;

export type SessionProviderId = (typeof SESSION_PROVIDER_IDS)[number];

export const SESSION_DIRECTORY_IDS = [
  "codex",
  "claude",
  "gemini",
  "grokbuild",
  "opencode",
  "openclaw",
  "hermes",
  "pi",
  "dsh",
  "kimi",
  "zcode",
  "qoder",
  "qwen",
  "workbuddy",
  "antigravity",
  "cursor",
  "kilocode",
  "cline",
  "goose",
  "zed",
  "mimocode",
  "reasonix",
  "continue",
  "crush",
  "teleagent",
] as const satisfies readonly SessionProviderId[];

export type SessionDirectoryId = (typeof SESSION_DIRECTORY_IDS)[number];

export const SESSION_DIRECTORY_LABEL_KEYS: Record<SessionDirectoryId, string> =
  {
    codex: "sessionSettings.directories.codex",
    claude: "sessionSettings.directories.claude",
    gemini: "sessionSettings.directories.gemini",
    grokbuild: "sessionSettings.directories.grokbuild",
    opencode: "sessionSettings.directories.opencode",
    openclaw: "sessionSettings.directories.openclaw",
    hermes: "sessionSettings.directories.hermes",
    pi: "sessionSettings.directories.pi",
    dsh: "sessionSettings.directories.dsh",
    kimi: "sessionSettings.directories.kimi",
    zcode: "sessionSettings.directories.zcode",
    qoder: "sessionSettings.directories.qoder",
    qwen: "sessionSettings.directories.qwen",
    workbuddy: "sessionSettings.directories.workbuddy",
    antigravity: "sessionSettings.directories.antigravity",
    cursor: "sessionSettings.directories.cursor",
    kilocode: "sessionSettings.directories.kilocode",
    cline: "sessionSettings.directories.cline",
    goose: "sessionSettings.directories.goose",
    zed: "sessionSettings.directories.zed",
    mimocode: "sessionSettings.directories.mimocode",
    reasonix: "sessionSettings.directories.reasonix",
    continue: "sessionSettings.directories.continue",
    crush: "sessionSettings.directories.crush",
    teleagent: "sessionSettings.directories.teleagent",
  };
